fix validation of version fields
The of address fields always checked for 4 parts instead of using the
specified length.

    ValueError: Value should be a string in the format of ID2.ID1.ID0, where 0 <= IDx <= 255